language: android
sudo: required
jdk: 
 - oraclejdk8


before_install:
 - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.1-bin.tar.gz
 - tar -xzvf apache-ant-1.10.1-bin.tar.gz
 - export PATH=`pwd`/apache-ant-1.10.1/bin:$PATH
 - echo $(ant -version)
    
env:
 global:
 - ANDROID_API=24
 - EMULATOR_API=21
 - ANDROID_BUILD_TOOLS=24.0.2
 - ADB_INSTALL_TIMEOUT=5 # minutes
 
android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - android-$EMULATOR_API_LEVEL
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-19 # google play services
 - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
 - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
 licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+
 
deploy:
  provider: heroku
  on: master
  # Change this in the future
  api_key:
    secure: nKaBKucKgzG7KKlku0O3Ker7Hr6r/eI+FxAYVUJi9IgVIzykdfYSjs1H1bP4XPUcvyckx14m9RnnXJoOxgXSEc9tx+XP3VAq+96a0uWNsfmtXmD+DVon7fszlg9GskbP+QngVY84Ug1vNzKiPtgZMDu7D7wWT0nh0td6OUUt2yJxkTtd66MU0+7T93q5Nyx3ode2EUnUVt4bWrdvSvlikKsjFFFq/2Zg6BtJo78VOYo7YIUMEDsEOW/XdefGj2CzjuC2WLqZGEB4LyEJGLSKVrXPuA973Rns4klCihI7cBqykgTlQL+42YmeA6WIuYxpueGm9jb2Q+AOzmdwfkbdZOkBP3n9oxiplCCu6EgRVegBqeEGH6ivOsGBv8a5VS6bym2exPA65AcaeS3Gq/SVe/HS7GP6m0J1Qt8UgQC4vVDLO4YFrRjfyGx44FDY2oDfV6r6X6zP4u6TK/bZ/fmLMWWCiOPnKX3xBqrzRbiaMci3pfJkEazsvjr8gJJqnuEJDHidx1BDPRsqp42PUXaGJEfyHtdJc4uoiFnY2miN1QR6j/z6Ano1H25b5Uw0Yw+b6HRbz7woX4OGm7XS/JbVAdo0+5IIUjYD0s5TZrynnetdEaZ0+okdkhcNUsd888M+/vW2+j0SYca43rbfLrv/54h7OsLF+k8J49Ed/FYLZlY=
